### ISSUE TITLE
run only generation sitemap

### ISSUE THREAD

**Issue by TrungThinhScorpius** [jbaubree/vite-plugin-sitemap#52]
i just want run only generation sitemap with one command line. instead of build whole project with command "npm run build". Can you help me!!!

**Comment by jbaubree** [comment]
Hi, with this plugin you will not be able to do that. If you are using `vite-plugin-pages` or `vite-ssg`, your can check this plugins [vite-plugin-pages-sitemap](https://github.com/jbaubree/vite-plugin-pages-sitemap) [vite-ssg-sitemap](https://github.com/jbaubree/vite-ssg-sitemap) who will work in dev mode.
If you are not, i will advise you to use [sitemap-ts](https://github.com/jbaubree/sitemap-ts) directly.
