### ISSUE TITLE
Support Vue Router

### ISSUE THREAD

**Issue by ericuldall** [jbaubree/vite-plugin-sitemap#58]
Any idea or plans on how we can support view router to generate paths in our sitemap?

**Comment by ericuldall** [comment]
Came up with a quick solution that parses my routes array into the dynamicRoutes array format:
```
import routes from './src/modules/routes';
const dynamicRoutes = (() => {
    let routeArray = [];
    const processPaths = (r, prefix) => {
        for (let route of r) {
            const sitemapConfig = route?.meta?.sitemap || {};
            if (sitemapConfig.ignore) {
                continue;
            }
            if (sitemapConfig.paths) {
                routeArray = [...routeArray, ...sitemapConfig.paths];
            } else {
                routeArray.push(route.path);
            }
            if (route.children) {
                processPaths(route.children, route.path);
            }
        }
        return routeArray;
    };
    return processPaths(routes);
})();
```

**Comment by jbaubree** [comment]
Hi @ericuldall, this Vite plugin is actually framework agnostic. If you are working specifically on Vue, you can maybe use [`vite-plugin-pages`](https://github.com/hannoeru/vite-plugin-pages) to auto-generate your routes and [vite-plugin-pages-sitemap](https://github.com/jbaubree/vite-plugin-pages-sitemap) to generate sitemap?

**Comment by ericuldall** [comment]
Ah, that makes sense. Well it's easy enough to support outside of the plugin.
