### ISSUE TITLE
Add additional sitemaps to robots.txt

### ISSUE THREAD

**Issue by ericuldall** [jbaubree/vite-plugin-sitemap#59]
It's common to have multiple `Sitemap:` directives in a robots.txt file.
Especially for retail sites that may have a large number of products that are frequently updated. Product sitemaps can be generated in realtime.

So, you may have something like this:
```
Sitemap: https://example.com/sitemap.xml <----- handles basic static pages, can probably get generated at buildtime
Sitemap: https://example.com/products_sitemap.xml <---- handles products, will be generated in realtime or server side as needed
```

See https://www.walmart.com/robots.txt for a realworld example

**Comment by jbaubree** [comment]
@ericuldall is this feature seems to work as you expect ? https://github.com/jbaubree/sitemap-ts/pull/90

**Comment by ericuldall** [comment]
That looks about right. Would it work with both relative and absolute urls?
I have a use case where some of my sitemaps will be hosted on a different subdomain.

**Comment by jbaubree** [comment]
Can you give me an example of urls ?

**Comment by ericuldall** [comment]
```
Sitemap: https://example.com/sitemap.xml
Sitemap: https://content.example.com/sitemap_products.xml
Sitemap: https://content.example.com/sitemap_collections.xml
```

**Comment by ericuldall** [comment]
As long as they are authenticated in robots.txt it's valid to point to a sitemap at any arbitrary domain.

**Comment by jbaubree** [comment]
https://github.com/jbaubree/sitemap-ts/pull/90/commits/c27dda03e813d6701ffe04a15fa4dd1300368ed6 is this better with url filter adition ?

**Comment by ericuldall** [comment]
Yes, reviewing your unit tests that seems to be optimal behavior!

**Comment by jbaubree** [comment]
Can you try to update `vite-plugin-sitemap` to `v0.5.3` and test this feature?

**Comment by ericuldall** [comment]
Works! Ty
