### ISSUE TITLE
issue with outDir

### ISSUE THREAD

**Issue by Pawanyy** [jbaubree/vite-plugin-sitemap#82]
error generating robots.txt & sitemap.xml in build if --outDir flag is passed in command

![image](https://github.com/user-attachments/assets/c56df908-c116-449b-8c7b-e31c0e1ac68d)

i was getting this issue in vercel ci & cd

**Comment by jbaubree** [comment]
Hi @Pawanyy , can you provide me a simple reproduction project ?
I think you forgot to add outDir in `vite-plugin-sitemap` config:

```
import Sitemap from 'vite-plugin-sitemap'

export default {
  plugins: [
    Vue(),
    Sitemap({
      hostname: 'https://example.com',
      outDir: 'dist5' // <= add this config
    }),
  ],
}
```

**Comment by Pawanyy** [comment]
Hi @jbaubree, thanks 👍 it worked after passing the outDir manually 😎
![image](https://github.com/user-attachments/assets/9af3163a-1d4c-4601-b639-69875ea51a12)
